config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/de')
  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
    resources :examples
    post '/examples/find'

    match 'search', as: 'main_search', via: :get, to: 'main#search'

    get '/' => 'examples#list'
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def search; end
end

app/views/main/_hero.html.erb
<section class="hero <%= local_assigns[:class_modifier].nil? ? '' : class_modifier %>"  data-temporary="true">
  <div class="hero-body">
    <div class="container">
      <% unless local_assigns[:subtitle].nil? %>
        <h3 class="subtitle"><%= subtitle %></h2>
      <% end %>
      <% unless local_assigns[:title].nil? %>
        <h2 class="title"><%= title %></h2>
      <% end %>
    </div>
  </div>
</section>

app/views/main/search.html.erb
<% provide(:title, I18n.t('main.search.title')) %>
<div class="columns">
  <div class="column is-2">
    <aside class="menu">
      <p class="menu-label"><%= I18n.t("main.search.search", :default => "Search") %></p>
      <ul class="menu-list">
        <% Structure.find_each do |s| %>
          <li>
            <%= link_to s.name, '', data: 'structure-form-' + s.id.to_s %>
          </li>
        <% end %>
      </ul>
    </aside>
  </div>
  <div class="column">
    <% Structure.find_each do |s| %>
      <article class="article box search-form" id="structure-form-<%= s.id %>">
        <%= form_tag(examples_find_path, method: 'post') do %>
          <%= hidden_field_tag 'structure_id', s.id %>
          <h2 class="title"><%= s.name %></h2>
          <div class="tile is-ancestor">
            <div class="tile is-parent">
              <div class="tile is-child notification is-success">
                <%= label_tag(:satisfies, I18n.t("main.search.satisfies", :default => 'Satisfies:'), class: 'label') %>
                <%= select_tag(:satisfies, options_for_select(s.properties.map { |p| [p.name, p.to_atom.id] }), multiple: true, class: 'multi-select') %>
              </div>
              <div class="tile is-child notification is-danger">
                <%= label_tag(:violates, I18n.t("main.search.violates", :default => 'Violates:'), class: 'label') %>
                <%= select_tag(:violates, options_for_select(s.properties.map { |p| [p.name, p.to_atom.id] }), multiple: true, class: 'multi-select') %>
              </div>
            </div>
          </div>
          <% unless s.building_blocks.empty? %>
            <div class="tile is-ancestor is-vertical">
              <% s.building_blocks.each_slice(2) do |slice| %>
                <div class="tile is-parent">
                  <% slice.each do |bb| %>
                    <%= render("building_blocks/search_properties_row", bb: bb)%>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
          <%= submit_tag(I18n.t('main.search.search_button'), class: 'button') %>
        <% end %>
      </article>
    <% end %>
  </div>
</div>