config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/de')
  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
    resources :examples
    post '/examples/find'

    match 'search', as: 'main_search', via: :get, to: 'main#search'

    get '/' => 'examples#list'
  end
end

app/models/building_block_realization.rb
class BuildingBlockRealization < ApplicationRecord
  belongs_to :example, touch: true
  belongs_to :building_block
  belongs_to :realization, class_name: 'Example'

  validates :example, presence: true
  validates :building_block, presence: true
  validates :realization, presence: true
  validates_with IncludesTest, a: 'building_block.structure.related_structures', b: 'realization.structure'
end

app/views/building_block_realizations/_show.html.erb
<div class="tile is-child">
  <div class="content box">
    <h4 class="title"><%= bbr.building_block.name %></h4>
    <p><%= link_to bbr.realization.description, example_path(:id => bbr.realization.id) %></p>
    <div class="tile is-ancestor">
      <div class="tile is-parent is-vertical">
        <article class="tile is-child notification is-success">
          <div class="content">
            <h5 class="title"><%= I18n.t("building_block_realizations.show.hardcoded_truths", :default => "Hardcoded Truths") %></h5>
            <ul>
              <% bbr.realization.hardcoded_truths.each do |atom| %>
                <%= render 'atoms/show', atom: atom %>
              <% end %>
            </ul>
          </div>
        </article>
        <% unless bbr.realization.hardcoded_falsehoods.empty? %>
          <article class="tile is-child notification is-danger">
            <div class="content">
              <h5 class="title"><%= I18n.t("building_block_realizations.show.hardcoded_falsehoods", :default => "Hardcoded Falsehoods") %></h5>
              <ul id="falsehoods">
                <% bbr.realization.hardcoded_falsehoods.each do |atom| %>
                  <%= render 'atoms/show', atom: atom, modifier: t('logic.is_not') %>
                <% end %>
              </ul>
            </div>
          </article>
        <% end %>
      </div>
    </div>
  </div>
</div>