config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/de')
  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
    resources :examples
    post '/examples/find'

    match 'search', as: 'main_search', via: :get, to: 'main#search'

    get '/' => 'examples#list'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ErDBeere</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag '/favicon.ico' %>
  </head>
  <body>
    <div class="container">
      <nav class="nav">
        <div class="nav-left">
          <a href="/" class="nav-item">
            <img src="/erdbeere.png">
            <h1>ErDBeere</h1>
          </a>
        </div>
        <div class="nav-center">
          <div class="nav-item">
            <a href="<%= main_search_path %>" class="button is-info is-outlined">
              <span class="icon">
                <i class="fa fa-search"></i>
              </span>
              <span><%= t('layouts.application.search') %></span>
            </a>
          </div>
        </div>
      </nav>
    </div>
    <% if flash.any? %>
      <% if not flash[:error].blank? %>
        <%= render("main/hero", class_modifier: "is-danger", subtitle: I18n.t("layouts.application.error"), title: flash[:error])%>
      <% elsif not flash[:warning].blank? %>
        <%= render("main/hero", class_modifier: "is-warning", subtitle: I18n.t("layouts.application.warning"), title: flash[:warning])%>
      <% else %>
        <%= render("main/hero", class_modifier: "is-notice", subtitle: I18n.t("layouts.application.notice"), title: flash.join("\n"))%>
      <% end %>
    <% else %>
      <% unless yield(:title).empty? %>
        <%= render("main/hero", class_modifier: "is-primary", title: yield(:title))%>
      <% end %>
    <% end %>
    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
    <footer class="footer">
      <div class="container">
        <div class="content has-text-centered">
          <p>
            <strong>ErDBeere</strong> <%= I18n.t("footer.is_on") %> <a href="https://github.com/oqpvc/erdbeere">GitHub</a>!
          </p>
          <p><small>Powered by <a href="http://rubyonrails.org">Rails</a>, <a href="http://bulma.io">Bulma</a>, <a href="http://mathjax.org">MathJax</a> and <a href="http://spacemacs.org">Spacemacs</a>.</small></p>
        </div>
      </div>
    </footer>
  </body>
</html>